Pim\Bundle\TextmasterBundle\Entity\Document:
    type: entity
    table: textmaster_document
    repositoryClass: Pim\Bundle\TextmasterBundle\Doctrine\Repository\DocumentRepository
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        projectId:
            type: integer
            column: project_id
        textmasterDocumentId:
            type: string
            column: textmaster_document_id
            nullable: true
        productId:
            type: integer
            column: product_id
        productIdentifier:
            type: string
            column: product_identifier
        productLabel:
            type: string
            column: product_label
        dataToSend:
            type: json
            column: data_to_send
        languageFrom:
            type: string
            column: language_from
        languageTo:
            type: string
            column: language_to
        status:
            type: string
            column: status
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            nullable: true
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
